### PR TITLE
fix: always save last position before jump

### PR DESCRIPTION
**Pull request by phanen**
## Checklist
- [x] Used only camelCase variable names.
- [x] If functionality is added or modified, also made respective changes to the
  README.md (the `.txt` file is auto-generated and does not need to be modified).
- [x] Used conventional commits keywords.

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Thanks for the PR. 

I am wondering, is there a reason to not to save the previous position in the jump list? Because I can see just adding this behavior without a setting.

**Comment by phanen** [comment]
To be consist with the default behavior of vim's builtin textobjects, I also think it's more reasonable to always save the position.

**Comment by chrisgrieser** [comment]
All right. One Last thing, could you add a comment for the purpose of the m`? It might be a bit looking at it later on otherwise

**Comment by phanen** [comment]
Added.

**Comment by chrisgrieser** [comment]
Thank you, and thanks very much for the PR itself!

**Pull request merged**
