### PR TITLE
refactor: expose common functions in `utils`, so users can easily code custom text objects

### PR DESCRIPTION
**Pull request by stevenxxiu**
Sometimes I want to use text objects that have use cases specific to me.

This exposes common functions used in `charwise-textobjs.lua` to `utils`, so users can easily code custom text objects. I think this will make the plugin more useful and flexible.

## Checklist
- [x] Used only camelCase variable names.
- [x] If functionality is added or modified, also made respective changes to the
  README.md (the `.txt` file is auto-generated and does not need to be modified).
- [x] Used conventional commits keywords.

### CODE REVIEW

**Comment by chrisgrieser** [comment]
1. I am somewhat opposed to exposing these functions, since exposing any sort of API carries the implicit promise of keeping them stable. And since they are somewhat main functions I'd probably work on in the feature, making them are subject to change. 
2. Also, if this were to be merged, it's not good practice to stuff everything into the utils module, especially if it is only going to be used in one module (the charwise objects) anyway. Moreover, has the bad side effect of creating an unnecessarily huge diff in the commit history.

**Comment by chrisgrieser** [comment]
1. As comment with `WARN` at the beginning

"Yes" to every question otherwise

**Comment by stevenxxiu** [comment]
I've addressed your points.

**Comment by chrisgrieser** [comment]
👍

**Pull request merged**
